baseURL= "/"
languageCode= "en-us"
title= "Hyperhidrosis Encyclopedia"
paginate = 5

[permalinks]
  blog = "/:filename/"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Find relevant information about Hyperhidrosis, Body Odour and general sweat disorder"
  image = ":filename"

[taxonomies]
  categories = "categories"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tips"
    pre = "tips"
    url = "/tips/"
    weight = 3
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 4
